2019-08-28 10:38:11,935 ERROR: Exception on /newservice [GET] [in c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  [Previous line repeated 976 more times]
RecursionError: maximum recursion depth exceeded
2019-08-28 10:39:01,707 INFO: MVR Database [in C:\Users\marks\Local Sites\MVR Flask Database\app\__init__.py:47]
2019-08-28 10:39:03,320 ERROR: Exception on /newservice [GET] [in c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  [Previous line repeated 976 more times]
RecursionError: maximum recursion depth exceeded
2019-08-28 10:39:11,033 ERROR: Exception on /newservice [GET] [in c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  [Previous line repeated 976 more times]
RecursionError: maximum recursion depth exceeded
2019-08-28 10:40:28,127 INFO: MVR Database [in C:\Users\marks\Local Sites\MVR Flask Database\app\__init__.py:47]
2019-08-28 10:40:30,163 ERROR: Exception on /newservice [GET] [in c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  [Previous line repeated 976 more times]
RecursionError: maximum recursion depth exceeded
2019-08-28 10:42:32,746 INFO: MVR Database [in C:\Users\marks\Local Sites\MVR Flask Database\app\__init__.py:47]
2019-08-28 10:42:34,878 ERROR: Exception on /newservice [GET] [in c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\marks\local sites\mvr flask database\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  File "C:\Users\marks\Local Sites\MVR Flask Database\app\routes.py", line 178, in newService
    form = newService()
  [Previous line repeated 976 more times]
RecursionError: maximum recursion depth exceeded
2019-08-28 11:53:22,154 INFO: MVR Database [in C:\Users\marks\Local Sites\MVR Flask Database\app\__init__.py:47]
2019-08-28 12:19:47,685 INFO: MVR Database [in C:\Users\marks\Local Sites\MVR Flask Database\app\__init__.py:47]
2019-08-28 12:19:56,616 INFO: MVR Database [in C:\Users\marks\Local Sites\MVR Flask Database\app\__init__.py:47]
2019-08-28 12:20:06,334 INFO: MVR Database [in C:\Users\marks\Local Sites\MVR Flask Database\app\__init__.py:47]
2019-09-06 10:57:55,071 INFO: MVR Database [in C:\Users\marks\Local Sites\MVR Flask Database\app\__init__.py:47]
