2019-08-15 15:41:55,349 ERROR: Exception on /ultrasound [POST] [in c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\engine\default.py", line 717, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1782, in process
    value = _strict_as_bool(value)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1757, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % value)
TypeError: Not a boolean value: '4seasons'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Mark\Local Sites\MVR database\MVR-Database\app\routes.py", line 105, in ultrasound
    db.session.commit()
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1027, in commit
    self.transaction.commit()
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\orm\session.py", line 494, in commit
    self._prepare_impl()
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\orm\session.py", line 473, in _prepare_impl
    self.session.flush()
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2459, in flush
    self._flush(objects)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\util\compat.py", line 154, in reraise
    raise value
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2557, in _flush
    flush_context.execute()
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
    insert,
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1138, in _emit_insert_statements
    statement, params
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\util\compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value.with_traceback(tb)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\engine\default.py", line 717, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1782, in process
    value = _strict_as_bool(value)
  File "c:\users\mark\local sites\mvr database\mvr-database\venv\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1757, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % value)
sqlalchemy.exc.StatementError: (builtins.TypeError) Not a boolean value: '4seasons'
[SQL: INSERT INTO "report_US" ("docSerialNum", patient, owner, species, breed, "sexPatient", "agePatient", "clinicalHistory", "SF_Liver", "SF_Spleen", "SF_Stomach", "SF_Pancreas", "SF_Intestines", "SF_Adrenals", "SF_LKidney", "SF_RKidney", "SF_Bladder", "SF_Sublum", "SF_Prostate", "SF_Uterus", "Conclusions_ALL", "FINDAS_ALL", date, "clinicSerialNum", "clinicName", doctor, mvr4seasons) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'docSerialNum': 'a', 'doctor': 'M', 'SF_Adrenals': 'n', 'owner': 'bbbbbbb', 'species': 'dogggie', 'SF_Pancreas': 'n', 'patient': 'Doobie', 'SF_Stomach': 'n', 'SF_Spleen': 'n', 'mvr4seasons': '4seasons', 'SF_RKidney': 'n', 'SF_Intestines': 'n', 'SF_Uterus': 'n', 'SF_Bladder': 'n', 'clinicName': 'T', 'SF_LKidney': 'n', 'agePatient': 34, 'clinicSerialNum': 'e', 'SF_Sublum': 'n', 'sexPatient': 'F', 'Conclusions_ALL': 'asfaesf', 'breed': 'no', 'FINDAS_ALL': 'asefaeser', 'date': '010219', 'SF_Prostate': 'n', 'clinicalHistory': 34, 'SF_Liver': 'n'}]]
2019-08-15 15:42:31,435 INFO: MVR Database [in C:\Users\Mark\Local Sites\MVR database\MVR-Database\app\__init__.py:47]
2019-08-15 15:42:38,036 INFO: MVR Database [in C:\Users\Mark\Local Sites\MVR database\MVR-Database\app\__init__.py:47]
2019-08-15 15:43:02,038 INFO: MVR Database [in C:\Users\Mark\Local Sites\MVR database\MVR-Database\app\__init__.py:47]
2019-08-15 15:45:06,360 INFO: MVR Database [in C:\Users\Mark\Local Sites\MVR database\MVR-Database\app\__init__.py:47]
2019-08-15 15:46:28,202 INFO: MVR Database [in C:\Users\Mark\Local Sites\MVR database\MVR-Database\app\__init__.py:47]
2019-08-15 15:49:14,178 INFO: MVR Database [in C:\Users\Mark\Local Sites\MVR database\MVR-Database\app\__init__.py:47]
2019-09-17 13:30:00,955 INFO: MVR Database [in C:\Users\Mark\Local Sites\MVR database\MVR-Database\app\__init__.py:47]
2019-09-17 13:30:18,139 INFO: MVR Database [in C:\Users\Mark\Local Sites\MVR database\MVR-Database\app\__init__.py:47]
2019-09-17 14:13:33,315 INFO: MVR Database [in C:\Users\Mark\Local Sites\MVR database\MVR-Database\app\__init__.py:47]
